### ISSUE TITLE
Newest Update 0.12.7 Crashes on startup.

### ISSUE THREAD

**Issue by Maxi90909** [dzwdz/chat_heads#100]
When I update Chat heads in MC Version 1.20.1 to the newest update, Minecraft crashes on startup.

[crash-2024-07-08_09.56.42-client.txt](https://github.com/user-attachments/files/16124598/crash-2024-07-08_09.56.42-client.txt)

**Comment by Fourmisain** [comment]
Ah, `@ModifyArgs` is broken on Forge, I forgor 💀

Gonna quickly revert that particular change.

**Comment by Fourmisain** [comment]
There we go!
