### ISSUE TITLE
Heads stop showing after a /whisper is sent to the player

### ISSUE THREAD

**Issue by CyberHydra** [dzwdz/chat_heads#101]
Any time you receive or send a /whisper to any player on the server, the heads stop showing in chat to any message after the whisper.

**Comment by Fourmisain** [comment]
Sorry for the delay, I'm currently super sick. Probably won't be back til a week or so.

What you're describing sounds like the server doesn't normally send sender UUIDs but still does so for whispers - which is more of a server issue.
Chat Heads "Smart Heuristics" will turn heuristics off completely when the server sends just one message with a sender UUID, which is most likely what you're seeing here.

Disabling Smart Heuristics (or setting the sender detection to Heuristic only) should fix the issue.

**Comment by CyberHydra** [comment]
No need to apologize. Sorry to heat about your current condition, I pray for a swift recovery :).

That's right, the server is in fact cracked and uses a fork of the NoChatReports plugin. I will test your suggestion later today when I have time and comment on this issue when possible, I appreciate the help.
