### ISSUE TITLE
[BUG] Avatar stays left, regardless of where the player's name is positioned.

### ISSUE THREAD

**Issue by EmptyDreams** [dzwdz/chat_heads#103]
As shown, even if the player's name appears in the middle of the sentence, the mod will still add the avatar to the far left of the chat message.

![image](https://github.com/user-attachments/assets/e767b27c-1a74-415d-b2c3-db13c316715e)

In the image, "Violetoast" is the player's name.

This message is sent by the server using `ServerPlayer#sendSystemMessage`, with the player's name obtained from `Player#name`.

Indeed, it would be more appropriate for the avatar to be displayed next to the player's name or not at all for system messages, as placing the avatar on the left can lead to confusion about the message's origin.

```
minecraft: 1.20.1
fabric loader: 0.15.11
fabirc api: 0.92.2
chat heads: 0.12.7
```

**Comment by Fourmisain** [comment]
Yeah, that's a current limitation of how Chat Heads renders the heads. Affects #68 too.
This needs a complete rewrite, though I can already see some issues with that way as well (like needing to find the head position even for messages that we don't scan for names - and mod compatibility as always).
I also feel that people will request adding heads onto **all** occurences of names, but I guess one can worry about that later.

May get on that once I'm fit again.

> Indeed, it would be more appropriate for the avatar to be displayed next to the player's name or not at all for system messages

The "not at all for system messages" is not doable on most servers since they commonly translate _all_ messages to system messages and don't leave any identifying sender information like UUIDs or `/tell` click events, so we have to scan for names, leading to false positives.
If you know your server doesn't do this, you can disable the "heuristic" sender detection or turn off handling of system messages in the config - wouldn't recommend either if you're planning to play on different servers though.

**Comment by EmptyDreams** [comment]
> Yeah, that's a current limitation of how Chat Heads renders the heads. Affects #68 too. This needs a complete rewrite, though I can already see some issues with that way as well (like needing to find the head position even for messages that we don't scan for names - and mod compatibility as always). I also feel that people will request adding heads onto **all** occurences of names, but I guess one can worry about that later.
> 
> May get on that once I'm fit again.
> 
> > Indeed, it would be more appropriate for the avatar to be displayed next to the player's name or not at all for system messages
> 
> The "not at all for system messages" is not doable on most servers since they commonly translate _all_ messages to system messages and don't leave any identifying sender information like UUIDs or `/tell` click events, so we have to scan for names, leading to false positives. If you know your server doesn't do this, you can disable the "heuristic" sender detection or turn off handling of system messages in the config - wouldn't recommend either if you're planning to play on different servers though.

I apologize for not noticing that these configurations could be modified in the configuration file.
I look forward to the mod making more eye-catching improvements in the future.

**Comment by Fourmisain** [comment]
After some cursed attempts...

<img src="https://github.com/user-attachments/assets/4dc50a11-bff7-4ffe-9eaf-9e2d8e9c88a9" width=50% height=50%>

(Rendering everywhere except where they should)

![cursed2](https://github.com/user-attachments/assets/0f523b77-8f77-4c5c-97c8-81cd1d9fe962)
(Literally everywhere!)
(And don't even get me started how cursed the code got in some attempts)

I finally got some success with a relatively simple solution!

<img src="https://github.com/user-attachments/assets/d1ecbdbb-71a4-42bc-8c9f-b26efda5fec2" width=50% height=50%>

It's still incomplete and probably incorrect (unicode stuff), but at least there's progress.

That's it, just a status report.
Will hopefully finish this in the next few days.

**Comment by Fourmisain** [comment]
Made a [test build](https://github.com/dzwdz/chat_heads/releases/tag/render-test), which seems to work but may have some kinks if you wanna give it a try.
You need to change the "Render Position" config option to "Before Name".

**Comment by Fourmisain** [comment]
Made a [new test build](https://github.com/dzwdz/chat_heads/releases/tag/render-test2).
Seems pretty stable, need backport the changes to test them for #68.

**Comment by Fourmisain** [comment]
Okay, tried backporting and running with [Chat Timestamps](https://modrinth.com/mod/plagues-chat-timestamps):
![dang](https://github.com/user-attachments/assets/98b3b16e-58f2-4f37-b48a-114817470a12)
And that's exactly what I feared would happen.
The message is modified _after_ the head and its position are already determined.

Okay, no problem, just find the position at a later time, fixed!
![f](https://github.com/user-attachments/assets/0ae4277c-c01f-4a6c-803d-fa6b05bfc6ba)

But I remember I intentionally placed the code that early for compatibility with [Compact Chat](https://modrinth.com/mod/compact-chat)... Let's see...
![aaaa](https://github.com/user-attachments/assets/e3187670-f9ee-478e-9161-3d453eabe3b3)

Darnit, how can this issue be so cursed?

**Comment by Fourmisain** [comment]
Okay, looks like I managed to fix that too - even though the two mods aren't really compatible anyway (whenever Compact Chat combines two messages into one, all the timestamps update to the current time).
Everything appears to work correctly with multiple players and even when `§` formatting is involved too!

![fixed](https://github.com/user-attachments/assets/06a240b6-ecd3-457d-81d2-9cdeb75e27ac)

So now I "just" need to clean up the code, remove an optimization and forward/backport everything for all versions...
