### ISSUE TITLE
1.21 Neo variant crashes when clicking `Config` in the mods list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [dzwdz/chat_heads#105]
[Log](https://gist.github.com/3gf8jv4dv/4509a5b3b50f4a31d41bb3be76f56aa9)

**Comment by Fourmisain** [comment]
Aha, there was a breaking change in 21.0.110-beta (3 weeks ago).
Gonna see if I can quickly patch that up.

**Comment by Fourmisain** [comment]
Fixed in 0.12.11!
