### ISSUE TITLE
Error in translation Pt_br

### ISSUE THREAD

**Issue by Kisedek** [dzwdz/chat_heads#107]
Erro log:
[Render thread/WARN]: Skipped language file: chat_heads:lang/pt_br.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 17 column 4 path $.text.autoconfig.chat_heads.option.handleSystemMessages.@Tooltip)

Cause: Missing comma at the end of line 16 of the Pt_br translation.

Solution: Place a comma at the end of line 16.

**Comment by Fourmisain** [comment]
Indeed!
Thanks for the report, will release a fix shortly.

**Comment by Fourmisain** [comment]
Fixed in 0.12.13!
