### ISSUE TITLE
Compat with Beautified Chat

### ISSUE THREAD

**Issue by suerion** [dzwdz/chat_heads#109]
Could you add compat with https://modrinth.com/mod/beautified-chat-server

Love both mods, but your mod overwrite some settings 

Thanks

**Comment by Fourmisain** [comment]
> but your mod overwrite some settings

What do you mean?

![fine](https://github.com/user-attachments/assets/e8b8986d-46bc-423f-8d1f-17f73542d1b2)
It seems to work perfectly fine.

**Comment by suerion** [comment]
Hey, yeah it works nice yet, don't know whats the issue was, thanks and sorry for your patient
