### ISSUE TITLE
Text goes out of the chat background on "Compact" chat setting with Optifine

### ISSUE THREAD

**Issue by eDexiam** [dzwdz/chat_heads#12]
![javaw_gNRs0Aa15v](https://user-images.githubusercontent.com/29255472/122966409-95ac2800-d389-11eb-97fd-5ef5e62d26a4.png)

The screenshot is the best way for me to explain the issue :P
Chat Heads: V0.2.0
Forge (1.16.5): 36.1.32

**Comment by dzwdz** [comment]
Sorry, but I don't support optifine - fixing some of the issues that it causes can be a bit of a pain
