### ISSUE TITLE
Morpheus compatability

### ISSUE THREAD

**Issue by cpm9** [dzwdz/chat_heads#18]
Shows the wrong player head for Morpheus sleep chat messages in forge 1.16.5
![2021-11-12_21 14 23](https://user-images.githubusercontent.com/82549089/141606486-4617698b-927e-4d77-840a-4f99b86f5de8.png)
[https://www.curseforge.com/minecraft/mc-mods/morpheus](https://www.curseforge.com/minecraft/mc-mods/morpheus)

chat_heads_forge-0.2.0
Morpheus-1.16.5-4.2.70

**Comment by Fourmisain** [comment]
This is the same as #17...
