### ISSUE TITLE
Minecolonies compatibility

### ISSUE THREAD

**Issue by cpm9** [dzwdz/chat_heads#19]
Should minecolonies chat notifications get a player chat head? Personally I think its unnessesary and could be confusing. Of course its your call though. Thanks!

![2021-11-12_22 15 16](https://user-images.githubusercontent.com/82549089/141607930-10605c41-108a-48ef-8018-74f2bca885b2.png)

chat_heads_forge-0.2.0
minecolonies-1.0.0-RELEASE-universal
structurize-0.13.219-ALPHA-universal

**Comment by Fourmisain** [comment]
And this is the same as #17 too...
