### ISSUE TITLE
running on TLauncher?

### ISSUE THREAD

**Issue by MrSenet** [dzwdz/chat_heads#23]
I'm sorry: And how to use it on TLauncher? In my chat, instead of the skin, Steve.

P.s Maybe this is not the right place for the question, I apologize. I tried to ask on Sourseforge, my message got into spam. And I also do not know where to write, I do not understand English well, I write through a Translator.

**Comment by Fourmisain** [comment]
[Please don't use TLauncher.](https://github.com/dzwdz/chat_heads/issues/21#issuecomment-980067442)

TLauncher is closed source, so we can't fix any issues with it.
TLauncher is also **illegal**, so we _won't_ fix any issues with it.
