### ISSUE TITLE
Suggestion: Add Chat Heads to Modrinth

### ISSUE THREAD

**Issue by max-aider** [dzwdz/chat_heads#27]
That's it

**Comment by Nephwren** [comment]
I also agree.

**Comment by srnyx** [comment]
@dzwdz please do this!!

**Comment by srnyx** [comment]
Or @Fourmisain, I'm not sure

**Comment by Fourmisain** [comment]
There we go, the project is now up [on Modrinth](https://modrinth.com/mod/chat-heads)!
