### ISSUE TITLE
please publish releases on github releases page

### ISSUE THREAD

**Issue by gmankab** [dzwdz/chat_heads#29]
i can't open curseforge page, also curseforge is so slow and buggy, so please publish releases on github releases page

**Comment by Fourmisain** [comment]
You can now get the mod [on Modrinth](https://modrinth.com/mod/chat-heads) too!
I think that's a way better alternative than doing github releases (due to version/loader filtering etc).

**Comment by gmankab** [comment]
> You can now get the mod [on Modrinth](https://modrinth.com/mod/chat-heads) too! I think that's a way better alternative than doing github releases (due to version/loader filtering etc).

thanks bro
