### ISSUE TITLE
Player heads in username autocompletion

### ISSUE THREAD

**Issue by Ryhon0** [dzwdz/chat_heads#38]
Are there any plans for rendering the player head when tab completing usernames and if not, would it be something you're willing to add to this mod?

**Comment by Fourmisain** [comment]
![mockup](https://user-images.githubusercontent.com/8464472/219872400-fc387fb2-9bb2-4523-aae6-fd07405a8dd0.png)
So just as a mockup, you mean something like this?

**Comment by Ryhon0** [comment]
Yeah, something like that for both auto completion provided by a command and from the player list

**Comment by Fourmisain** [comment]
"from the player list"...? What do you mean by that?

**Comment by Ryhon0** [comment]
No, I mean it should appear when typing regular chat messages too. For example if you typed `For` and pressed tab, it shows a list of players with a name that starts with `For`, this list is based on the player list

**Comment by Fourmisain** [comment]
TIL you can auto-complete player names in regular chat!

I already have an almost working version of this now - and it does work with the regular player name suggestion too.

I say "almost working", but there might be more work involved.
If you autocomplete a name as the first word, the player head will be offscreen. Moving the text to the right is not easy, so I'm not sure if I should actually fix this (plus I like the way the names align in the picture above).
It's currently also possible non-player suggestions get a chat head, e.g. if there's a player called -42 or something.

So yeah, probably won't be done today, but it will surely come!

**Comment by Fourmisain** [comment]
I guess I lied, new version 0.10.0 is up!

Only did it for 1.19.3, lemme know if you need a backport.

**Comment by Ryhon0** [comment]
Thanks! 1.19.2 would be great!

**Comment by Fourmisain** [comment]
There ya go!
