### ISSUE TITLE
Debug print

### ISSUE THREAD

**Issue by Fourmisain** [dzwdz/chat_heads#4]
The `print = true` at
https://github.com/dzwdz/chat_heads/blob/323aa93446ea7fd2d8a1902ea4bfdad78f05f8c6/fabric/src/main/java/dzwdz/chat_heads/mixin/ChatComponentMixin.java#L38-L45
prints a huge 47 line debug variable table and should be removed since we know it is working correctly.

**Comment by dzwdz** [comment]
Whoops, I've thought I'd removed that. Thanks!
