### ISSUE TITLE
Message Verification Indicators are under text with Chat Heads

### ISSUE THREAD

**Issue by Hi-ImKyle** [dzwdz/chat_heads#45]
Have Chat Heads installed and go on a server with unverifiable/whatever messages and the indicator that is present at the very end of the message is hidden under the text. This is because the Chat Head icon is shifting the text and the indicator isn't included in what is being shifted

I first experienced this with No Chat Report's Encrypted Messages Indicator
![image](https://user-images.githubusercontent.com/25551312/227770632-28d7016e-c98c-458c-98bd-c25cc1bd18fa.png)

This does the same thing for the vanilla indicators for message verification.

Note: If a message takes up more than one line then the indicator is fine

Game Version: 1.19.2
Loader: Quilt 18.2 + Quilted API 4.0.0
Chat Heads version: 0.10.7

**Comment by Fourmisain** [comment]
Just saw your comment on CF and was wondering when those indicators appear - haven't yet meddled with 1.19 multiplayer and debugging is gonna be easier when I can see what I'm doing.

I tried setting up a simple 1.19.4 server with default settings (so `online-mode` and `enforce-secure-profile` are both true), installed No Chat Reports only on the client but didn't see any indicators at all, even though "Show encryption indicators" is set to true.
Can you not see indicators on your own messages or what am I missing?
Gonna try 1.19.2 now...

**Comment by Fourmisain** [comment]
![done](https://user-images.githubusercontent.com/8464472/227773217-a31b5643-93e7-4efd-bcdf-ce08df84c350.png)

**Comment by Hi-ImKyle** [comment]
I'll be honest, I can't tell if you showing me the image is a fix or if the issue doesn't appear on your end.

**Comment by Fourmisain** [comment]
Yep, I fixed it and new versions are up!

> I'd also like to stress this isn't a No Chat Reports isolated issue.

Yes, luckily!
No Chat Reports is making use of the vanilla icon code so we didn't have to add any mod specific code, that would have been annoying.

**Comment by Hi-ImKyle** [comment]
You work fast, I love it. Thanks for fixing this 👍
