### ISSUE TITLE
[Bug] Message with multi-line have multi head on start

### ISSUE THREAD

**Issue by Guanran928** [dzwdz/chat_heads#5]
Message with multi-line have multi head on start

Image
![image](https://user-images.githubusercontent.com/68757440/105432231-195fbe00-5c0c-11eb-9b19-7e291825e17d.png)

Fabric 0.11.1
Minecraft 1.16.5
Mod version 0.2.1

**Comment by dzwdz** [comment]
fixed it in 0.2.2, which should be up on curseforge soon
