### ISSUE TITLE
Crash when try to load minecraft 1.20 with chat heads

### ISSUE THREAD

**Issue by Rozbiynk** [dzwdz/chat_heads#52]
Seems other mods have problem with chat sign
Crash report - https://mclo.gs/PHlqwo6
Latest log - https://mclo.gs/OqGJON1

**Comment by Fourmisain** [comment]
Hm... Chat Signing Hider seems to work.
ShutUpMojang on the other hand looks incompatible in multiple ways. You can just remove that mod since Chat Signing Hider already removes the "Messages cannot be verified on this server" anyways.
(Or you should probably use No Chat Reports instead.)

The Mixin error I got with ShutUpMojang is different to your log, so it might be yet another conflicting mod, but it's not clear which one.

You can try disabling a hand full of mods and see if it stops crashing. If so, we know that the conflicting mod was one of the ones you last disabled.

**Comment by Rozbiynk** [comment]
seems incompatible was in chat signing hider. Thank for help

**Comment by Fourmisain** [comment]
Ah, I think this is probably not the last we're gonna see of this crash.

It's not actually a conflict with Chat Signing Hider but it's a mixin ordering issue with another mod.
Removing Chat Signing Hider randomly changed the mixin order, allowing Chat Heads to run first, which circumvented (solved) the issue.

I'm still not sure which mod is the true cause (apart from ShutUpMojang).

But oh well, if it works, it works.

Let me know if you run into this again, maybe I'll be able to find the true cause next time.

**Comment by Rozbiynk** [comment]
it still crash even without chat signing hider and shut up mojang(
use 0.10.18 version

**Comment by Rozbiynk** [comment]
same error

**Comment by Rozbiynk** [comment]
https://mclo.gs/HgfP2W3

**Comment by Fourmisain** [comment]
I installed every mod that sounded suspicious and was *finally* able to reproduce the crash!
It's a conflict with EssentialClient.
I've reported the Mixin conflict, hopefully to be fixed soon.

**Comment by Rozbiynk** [comment]
tysm, i even cant imagine that was that mod, lol

**Comment by Fourmisain** [comment]
Oh right, while I was looking at the mods I found that Disable Insecure Chat Toast is covered by what gatekeep does and I believe they can cause a crashing Mixin conflict too ([`@Redirect`](https://github.com/NikitaCartes/DisableInsecureChatToast/blob/eb40f210d776b4b1463030651c03887cc5d7bd83/src/main/java/xyz/nikitacartes/disableinsecurechattoast/mixin/ClientPlayNetworkHandlerMixin.java#L12-L14) vs [`@Inject`](https://github.com/jadeposting/gatekeep/blob/022c31bedfec38c9553b4657a9d3e7e66939eae0/src/main/java/dev/jadeposting/gatekeep/mixins/ClientPacketListenerMixin_RemoveToast.java#L12-L20) with the same target), so you should uninstall Disable Insecure Chat Toast.

Haha, I see you had issues with similar mods already https://github.com/jadeposting/gatekeep/issues/3 😅

**Comment by Rozbiynk** [comment]
yes, i have problem with it when install 1.20...
