### ISSUE TITLE
crash with latest version

### ISSUE THREAD

**Issue by DelviousCrafts** [dzwdz/chat_heads#57]
Latest version of Chat Heads crashes upon login attempt due to cape texture. 

[Crash Report](https://gist.github.com/DelviousCrafts/95b9e6d4b2c0b32ea9b6b4d7457eddf0)

[Latest Log](https://gist.github.com/DelviousCrafts/33e69165517df5e70d1d49eaaeebb983)

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.17
- Chat Heads: 0.10.17

**Comment by N0aW** [comment]
Same problem. Game crashes when I try to join a server.

Versions:
- Minecraft: 1,20.1
- Fabric: 0.14.21
. Chat Heads: 0.10.17

**Comment by Fourmisain** [comment]
Uh oh, it's not supposed to read the cape texture!
Another one of those things where you're wondering how it even worked before.

I think I'll unpublish the current version until I fix the issue.

**Comment by Fourmisain** [comment]
Alright, fixed in 0.10.18!
New versions are up on Modrinth and CurseForge (currently waiting for approval).
