### ISSUE TITLE
[Feature request] Timestamps.

### ISSUE THREAD

**Issue by RDKRACZ** [dzwdz/chat_heads#6]
Since this mod already adds something before the actual message would it be possible to add a timestamp too?

![image](https://user-images.githubusercontent.com/43277609/106206822-011a1100-61c1-11eb-9e7c-980079109324.png)

**Comment by dzwdz** [comment]
i don't see the point, there are already many other mods that do that (e.g. tweakeroo)

**Comment by RDKRACZ** [comment]
Are you sure it's available in the tweakeroo? I can't see any info about it.

**Comment by RDKRACZ** [comment]
Tested it and I couldn't find it in the config via ModMenu.

**Comment by dzwdz** [comment]
![image](https://user-images.githubusercontent.com/21179077/106381887-23c44980-63bc-11eb-8412-672525260691.png)
Maybe you're on some older version?

**Comment by RDKRACZ** [comment]
Sure I was, weird as I'm checking curseforge daily.
