### ISSUE TITLE
crash client 1.19.2 Forge

### ISSUE THREAD

**Issue by GitJhopa** [dzwdz/chat_heads#64]
[crash-2023-08-17_16.28.28-client.txt](https://github.com/dzwdz/chat_heads/files/12379286/crash-2023-08-17_16.28.28-client.txt)
[crash-2023-08-18_15.34.51-client.txt](https://github.com/dzwdz/chat_heads/files/12379287/crash-2023-08-18_15.34.51-client.txt)

**Comment by Fourmisain** [comment]
You're using an old Chat Heads version (0.10.16), this issue should be fixed in newer versions.
Updating might even solve the issue with HD skins #63 you were having.
