### ISSUE TITLE
Show chat heads after timestamps from e.g. Plague's Chat Timestamps

### ISSUE THREAD

**Issue by ghost** [dzwdz/chat_heads#68]
Would this be feasible, or should I request this from the timestamp mod's dev instead?

**Comment by Fourmisain** [comment]
I don't think this is really feasible on either end.
The way Chat Heads currently works is by moving the whole text (including the mouse over hitboxes etc) to make space for rendering the heads. In other words, it can't put them in the middle of text, only at this very specific location.
Ideally the heads would just be characters inside the text, but I think the heads have a different size from the characters, meaning the whole vanilla text rendering and splitting logic would have to be rewritten (no thanks).

Only solutions I can currently think of are hacks that nobody should use, so yeah, this is a bit of a 🤷 moment.

**Comment by Fourmisain** [comment]
This is _finally_ solved with the new "Before Name" rendering in 0.13!
