### ISSUE TITLE
Clientside chat messages use the head of the previous message when they should have no head

### ISSUE THREAD

**Issue by 1stmemberoftheDKcrew** [dzwdz/chat_heads#7]
<h2>The problem</h2>
<p>Client (but not server messages) that aren't actually chat messages will use the head of the previous message. (when testing online it would also use the head of other players, not just your player)</p>
<br>
<img width="544" alt="image" src="https://user-images.githubusercontent.com/48365836/111219639-a7be4380-85ae-11eb-9cf1-69ea5cf3bf7f.png">

<h2>How to test in singleplayer: </h2>
<ul>
<li> type something in chat</li>
<li> use any mod with clientside chat feedback, do something to send the feedback (I used meteor client)</li>
<li> /tellraw @p "goodmorning kanye"  (or any other sample text)</li>
<li> trigger the clientside chat message again</li>
<li> compare</li>
</ul>

**Comment by dzwdz** [comment]
![image](https://user-images.githubusercontent.com/21179077/111965515-198a1600-8af6-11eb-89e1-4fb0d907d583.png)
seems fine to me

**Comment by dzwdz** [comment]
i looked at the source of meteor client, and they are adding the chat messages in a weird way - in case you want to create an issue on their gh, this is the function that they should use:
InGameHud::addChatMessage
