### ISSUE TITLE
Its just not working for me 

### ISSUE THREAD

**Issue by sprigankkkrkkkriem** [dzwdz/chat_heads#70]
Im on Fabric for 1.20.1 and its just not displaying the heads 
https://github.com/dzwdz/chat_heads/assets/72741679/4ff2a5a2-c7fb-4e77-8442-2093c62c6030

**Comment by Fourmisain** [comment]
First of all, are you sure you installed the [Fabric version](https://legacy.curseforge.com/minecraft/mc-mods/chat-heads/files/4766867) of Chat Heads, not the Forge one?

Do the heads appear in singleplayer?
If so: Try changing Chat Heads' sender detection settings to "Heuristic Only", some servers require that. (You need Mod Menu and Cloth Config API to change the settings).
If not: What other mods have you installed?

**Comment by sprigankkkrkkkriem** [comment]
it´s not working for me either in single player
https://github.com/dzwdz/chat_heads/assets/72741679/61c91afb-6d30-494e-8364-c6ec3acd1b6f
these mods are installed and they work 

https://github.com/dzwdz/chat_heads/assets/72741679/cff81f55-2e0a-4ea3-8ac9-038d867c9900
and these settings still not working in single or multiplayer

**Comment by Fourmisain** [comment]
Ah, it's OptiFine yet again.

As with #54, #55:
We can't support OptiFine as it's closed source. Use Sodium and co instead. Here's a good [list of alternatives](https://fabricmc.net/wiki/optifine-alternatives).
