### ISSUE TITLE
能开发成插件并且支持低版本吗？如果可以，那真是太棒了！

### ISSUE THREAD

**Issue by jiahe666666** [dzwdz/chat_heads#71]
Can it be developed as a plug-in and support a lower version? If so, that would be great! Thanks to the author! I wish you good health and all the best!!
能开发成插件并且支持低版本吗？如果可以，那真是太棒了！感谢作者！祝您身体健康万事如意！！！

**Comment by Fourmisain** [comment]
We recently learned that server plugins can add arbitrary images, including chat heads, to the chat by using a custom font (requiring a server resource pack), see #69.
Ryhon0 is currently developing one, so you may keep an eye out for that.
Though I have no idea if it will support earlier versions - I wouldn't hold my breath on that.

Apart from that, there are no current plans to make a plugin ourselves, or support versions earlier than 1.16.

DeepL
我们最近了解到服务器插件可以通过使用自定义字体（需要服务器资源包）在聊天中添加任意图像，包括聊天头像，请参见 #69。
Ryhon0 目前正在开发一个插件，所以你可以留意一下。
虽然我不知道它是否支持早期版本，但我不会对此抱有任何希望。

除此之外，我们目前没有制作插件的计划，也不支持 1.16 之前的版本。

**Comment by jiahe666666** [comment]
感谢您的回复，这对我有很大帮助！谢谢您！

**Comment by jiahe666666** [comment]
@Fourmisain 如果我想在1.7.10实现这个效果，你认为能否做到？

**Comment by Fourmisain** [comment]
I don't know anything about 1.7.10 modding, but I think server resource packs were already a thing then, so theoretically it should be possible.

DeepL
我对 1.7.10 版的改装一无所知，但我认为当时已经有服务器资源包了，所以理论上应该是可行的。

**Comment by jiahe666666** [comment]
非常感谢！

**Comment by jiahe666666** [comment]
But I heard other people say that the avatar feature will come after 1.8
但是我听其他人说1.8以后才有的头像功能

**Comment by Fourmisain** [comment]
By "avatar feature" they probably mean the player heads in the TAB online player list?
While those weren't in 1.7.10, it doesn't really matter because player skins where in the game from day 1.
When you got the skin, you got the player head.
A server plugin can load the skins, cut out the head and generate and send text that looks like the player head.
A client-side mod could also do the same and add heads to the online player list.
Theoretically.

DeepL
他们所说的 "头像功能 "可能是指 TAB 在线玩家列表中的玩家头像？
虽然 1.7.10 中没有这些功能，但这并不重要，因为玩家皮肤从第一天起就出现在游戏中。
有了皮肤，就有了玩家头像。
服务器插件可以加载皮肤，剪切出头像，生成并发送与玩家头像相似的文本。
客户端 mod 也能做到这一点，并将头像添加到在线玩家列表中。
在理论上。

**Comment by jiahe666666** [comment]
Yes, the "avatar feature" refers to the avatar of the player in the TAB online player list. Thank you for your answer and my highest respect to you!
是的，“头像功能 ”是指 TAB 在线玩家列表中的玩家头像。感谢您的回答，向您致以最高的敬意！

**Comment by jiahe666666** [comment]
我想学习如何制作插件和mod，但是我只记住了如何写在控制台输出hello！world！的插件........
我不知道该从何学起，请问我能请你当我的老师吗？我可以给予您报酬！
I wanted to learn how to make plugins and mods, but I only remembered how to write hello in the console output! The world! Plugin for........
I don't know where to start. May I ask you to be my teacher? I can pay you!

**Comment by Fourmisain** [comment]
Sorry, I've never written a server plugin, so I couldn't really teach you. The language barrier would make this pretty hard too I'm sure.
Afaik, modding for 1.7.10 is also completely different than for newer versions. Most "modern" client mods, including Chat Cheads, use Mixin, and I'm not sure if that is even used on 1.7.10 as it is unsupported and difficult to get running. Other solutions modify bytecode (essentially a form of assembly), which is another thing to learn and way harder to get right.
There surely have to be dedicated modding communities for 1.7.10 specifically somewhere, but I have no idea where.

DeepL
对不起，我从来没有编写过服务器插件，所以真的没法教你。我相信语言障碍也会让这变得很困难。
据我所知，1.7.10 版的修改也与新版本完全不同。大多数 "现代 "客户端修改器（包括 Chat Cheads）都使用 Mixin，但我不确定 1.7.10 是否也使用 Mixin，因为它不受支持且难以运行。其他解决方案会修改字节码（本质上是汇编的一种形式），这又是另一个需要学习的东西，而且很难做到正确。
肯定有专门针对 1.7.10 的修改社区，但我不知道在哪里。

**Comment by jiahe666666** [comment]
好吧，不好意思，打扰了，昨天我生病了所以没回复您。但是还是祝您天天开心

Well, I'm sorry to bother you, but I was sick yesterday so I didn't reply to you. But still wish you happy every day
