### ISSUE TITLE
Support pulling name heuristics from hover components

### ISSUE THREAD

**Issue by Nemo157** [dzwdz/chat_heads#72]
On a server I'm on using [Styled Nicknames](https://github.com/Patbox/StyledNicknames) we have the player's account name displayed in a hover text:

![image](https://github.com/dzwdz/chat_heads/assets/81079/a46a41bc-83fa-41a9-a9e5-340d774ca054)

<details><summary>json text components for the message</summary>

```json
[
  {
    "color": "gold",
    "insertion": "Nemo157",
    "clickEvent": {
      "action": "suggest_command",
      "value": "/tell Nemo157 "
    },
    "hoverEvent": {
      "action": "show_text",
      "contents": {
        "text": "Nemo157"
      }
    },
    "extra": [
      {
        "text": "Tést"
      }
    ],
    "text": ""
  },
  {
    "text": ": "
  },
  {
    "text": "test"
  }
]
```
</details>

It would be useful if Chat Heads could look into these text components when using heuristics to find the name.

**Comment by Fourmisain** [comment]
Implemented in 1d35f87a996fb15537f7c48df2f305925f33bd06, new versions 0.10.23 are up!

Since hover text could be anything (you never know what mods/plugins are gonna do), I instead checked the sender decorator click event for a `/tell` command.
