### ISSUE TITLE
Not working with Optifine

### ISSUE THREAD

**Issue by or1n** [dzwdz/chat_heads#79]
It's not working together with optifine on Minecraft 1.20.1
Without it, it works fine on my client but with it dissapears.

If this is known, could add it to the Modrinth and Curseforge page, took me a while to find out.

Nice mod nontheless and thanks for all your hard work!

**Comment by Fourmisain** [comment]
[It is know](https://github.com/dzwdz/chat_heads/issues?q=is%3Aissue+optifine).

I added a note to the description, should have done that much earlier.

Also, highly recommend to check out [OptiFine alternatives](https://fabricmc.net/wiki/community:optifine_alternatives)!

**Comment by vinnyg0621** [comment]
shit, I really need optifine and all the features it has 😢, and this mod doesn't work with it is such a bummer 😭😭😭😭

**Comment by Fourmisain** [comment]
Literally all features of OptiFine have been reimplemented by compatible open source mods - and I doubt you need all of them.

See: [OptiFine alternatives](https://fabricmc.net/wiki/community:optifine_alternatives) (plus for capes you can e.g. use the [Capes](https://modrinth.com/mod/capes) mod.)

**Comment by vinnyg0621** [comment]
> [It is know](https://github.com/dzwdz/chat_heads/issues?q=is%3Aissue+optifine).
> 
> I added a note to the description, should have done that much earlier.
> 
> Also, highly recommend to check out [OptiFine alternatives](https://fabricmc.net/wiki/community:optifine_alternatives)!

*it is _known_.
