### ISSUE TITLE
Don't show heads on non-player messages

### ISSUE THREAD

**Issue by nchristopher** [dzwdz/chat_heads#8]
Since the client (_usually_) recieves a UUID with each player-made chat message, you could filter-out non-player messages, and not show an indent on them.

It's not a big deal, but it'd be nice for that space to not appear unneccesarily.

**Comment by dzwdz** [comment]
> usually
A lot of servers don't send the UUID, and I don't want to break the mod on those. Also, since that would misalign player and non-player messages, it'd probably look worse

**Comment by nickhasoccured** [comment]
You have a fair point. How does the mod currently get player heads? I just assumed it was through the message's UUID.

**Comment by dzwdz** [comment]
If the message has an UUID it just uses it, otherwise it searches for any player nicks in the message - that's usually the sender

**Comment by nickhasoccured** [comment]
If possible, could you add a config option to _not_ add the indent when there's no UUID in the message? If not, it's totally understandable.
