### ISSUE TITLE
Check if `Minecraft#getConnection()` is NULL before using it in `CommandSuggestionSuggestionsListMixin`

### ISSUE THREAD

**Issue by Keksuccino** [dzwdz/chat_heads#82]
Hi, dev of FancyMenu here!

One of my users reported a crash related to our mods and it happens because I use suggestion lists for text input boxes in other parts of GUIs (also when no world/server is loaded).
Since you call `Minecraft#getConnection()` in `CommandSuggestionSuggestionsListMixin`, the game will crash when the player is not in a world/server.

Please add NULL checks for both calls to `Minecraft#getConnection()`:

https://github.com/dzwdz/chat_heads/blob/c121d8a84540c4054f9fe0ddbc21c3415c9cb3d1/common/src/main/java/dzwdz/chat_heads/mixin/CommandSuggestionSuggestionsListMixin.java#L51
https://github.com/dzwdz/chat_heads/blob/c121d8a84540c4054f9fe0ddbc21c3415c9cb3d1/common/src/main/java/dzwdz/chat_heads/mixin/CommandSuggestionSuggestionsListMixin.java#L69

Thank you very much and have a great day!

**Comment by Fourmisain** [comment]
Fixed!

0.10.31 is out!

**Comment by Keksuccino** [comment]
Works great now, thank you very much!
