### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by Etanarvazac** [dzwdz/chat_heads#86]
Client Version: Fabric 1.20.4
Server Version: 1.20.4 Velocity

Nicknames? Yes
Format: `<prefix> <nickname>: <message>`
Output after adding my own nickname:
<img width="377" alt="image" src="https://github.com/dzwdz/chat_heads/assets/55290878/1e258abc-fa85-456d-9ebb-9a94ae57d7a8">

**Comment by Fourmisain** [comment]
What does it show in the tab menu / player list?
If you click a player's name, do you get a `/tell` command to DM that player?

If the nicknames don't match either the tab menu name or the profile name, there's no way Chat Heads can associate the message with its sender.

What you can try is to add a name alias in the config:
`Etanarvazac -> your_profile_name`

**Comment by Fourmisain** [comment]
Also, if the chat messages don't that clickable `/tell` command, that is an issue that should be reported to the used chat plugin.

**Comment by Etanarvazac** [comment]
The server has custom click and hover events on player name. So that wouldn't work as it is. I made a dummy server and it doesn't even work on there. Yes, I am using 0.10.32
![image](https://github.com/dzwdz/chat_heads/assets/55290878/3bd2510b-41b2-4dcd-9a69-68e8f53d57cc)

**Comment by Fourmisain** [comment]
> I made a dummy server and it doesn't even work on there.

Is that dummy server modded or not?

> It doesn't even work on local worlds both offline and open to LAN:

Wait, it doesn't even work in singleplayer?
Then this is a mod conflict with some mod you've installed.

Please send your mod list so I can have a look.
I hope you're not using OptiFabric, since OptiFine is known to break this mod since around 1.20.1.

**Comment by Fourmisain** [comment]
> I hope you're not using OptiFabric, since OptiFine is known to break this mod since around 1.20.1.

Looking at this again, the font your chat uses looks suspiciously like a HD font.
Here's the obligatory tip to use [Sodium and co](https://fabricmc.net/wiki/community:optifine_alternatives) instead.

Since there's no further info, I'm gonna close this issue.
