### ISSUE TITLE
[Forge 1.20.1] Chat heads not showing up on Quark's item sharing module

### ISSUE THREAD

**Issue by NeuTraLZero** [dzwdz/chat_heads#87]
Forge version: 47.2.0
Chat Heads version: 0.10.32
Quark version: 4.0-441

[latest.log](https://github.com/dzwdz/chat_heads/files/15190804/latest.log)

![image](https://github.com/dzwdz/chat_heads/assets/43245485/a346e560-1614-4e1a-81b8-d936deff5784)

**Comment by Fourmisain** [comment]
Aha! Quark completely bypasses the chat system, sending custom packets and [printing the message manually](https://github.com/VazkiiMods/Quark/blob/527ba3f3a08e03883839758a964b6f776e015078/src/main/java/org/violetmoon/quark/base/network/message/ShareItemS2CMessage.java#L35-L39).
I think this will require some compatibility code, which I'll look into tomorrow.

**Comment by Fourmisain** [comment]
Implemented in 0.10.33.

**Comment by NeuTraLZero** [comment]
Awesome, thank you!
