### ISSUE TITLE
Forge 1.20.4 Version of Chat Heads Not Working!

### ISSUE THREAD

**Issue by ZaryaWulf** [dzwdz/chat_heads#93]
So I'm trying to use the mod to see player heads when they talk in the chat, but their player heads aren't showing up. I've tried messing with all of the settings in the config, and nothing has worked. Can anyone help me? We are using the Hexnicks plugin if that helps as well, cause that allows people to change their nickname and color.

**Comment by Fourmisain** [comment]
Step by step:
Make sure you're not using OptiFine, as it's known to be incompatible with Chat Heads.
Use open source alternatives like [Sodium and co](https://fabricmc.net/wiki/community:optifine_alternatives) instead. (The list is for Fabric, but there's Forge equivalents as well.)

If you're not using it, can you check if the chat heads appear in singleplayer?
If they do not, then there's a conflict with another mod you've installed, in which case I need your modlist, so I can track down the issue.

If they do, then we known it's an issue with the server handling.
To explain how that works:
Chat Heads checks if a player name appears inside a message.
A player name can be the player's profile name, or the diplay name that is shown in the tab player list.
If neither of those names appear in the message, Chat Heads can't really figure out who owns the message and the only workaround is to add name aliases in the settings.

For example, if you have a player with
profile name: `edd`
display name: `[VIP] Eddy`
name inside the message: `Edgar`
then you can add a name alias `Edgar -> edd` (or `Edgar -> [VIP] Eddy`) and it should fix the issue.

**Comment by Fourmisain** [comment]
Closing this due to lack of information...
